// services/pdfService.js
import puppeteer from "puppeteer";
import { generateReportHTML } from "../templates/reportTemplate.js";
import fs from "fs";

// Generate PDF from analysis data
export const generateAnalysisPDF = async (analysisData) => {
  let browser;

  try {
    console.log("Starting PDF generation");

    // Launch browser
    browser = await puppeteer.launch({
      headless: "new",
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-accelerated-2d-canvas",
        "--disable-gpu",
      ],
    });

    const page = await browser.newPage();

    // Generate HTML content
    const htmlContent = generateReportHTML(analysisData);

    // Set content
    await page.setContent(htmlContent, {
      waitUntil: "networkidle0",
    });

    // Generate PDF
    const pdfBuffer = await page.pdf({
      format: "A4",
      margin: {
        top: "20px",
        right: "20px",
        bottom: "20px",
        left: "20px",
      },
      printBackground: true,
    });

    console.log("PDF generated successfully");

    return pdfBuffer;
  } catch (error) {
    console.error("PDF generation error:", error);
    throw new Error(`Failed to generate PDF: ${error.message}`);
  } finally {
    if (browser) {
      await browser.close();
    }
  }
};

// Save PDF to file system
export const savePDFToFile = async (pdfBuffer, filename) => {
  try {
    const tempDir = "./public/temp";
    if (!fs.existsSync(tempDir)) {
      fs.mkdirSync(tempDir, { recursive: true });
    }

    const filepath = `${tempDir}/${filename}`;
    fs.writeFileSync(filepath, pdfBuffer);

    console.log("PDF saved to:", filepath);
    return filepath;
  } catch (error) {
    console.error("PDF save error:", error);
    throw new Error(`Failed to save PDF: ${error.message}`);
  }
};

// Generate health summary PDF
export const generateHealthSummaryPDF = async (summaryData) => {
  let browser;

  try {
    console.log("Generating health summary PDF");

    browser = await puppeteer.launch({
      headless: "new",
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });

    const page = await browser.newPage();

    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: 'Arial', sans-serif;
      margin: 40px;
      color: #333;
      line-height: 1.6;
    }
    .header {
      text-align: center;
      border-bottom: 3px solid #4CAF50;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      color: #4CAF50;
      margin: 0;
    }
    .patient-info {
      background: #f5f5f5;
      padding: 20px;
      border-radius: 8px;
      margin-bottom: 30px;
    }
    .section {
      margin: 30px 0;
    }
    .section h2 {
      color: #4CAF50;
      border-left: 4px solid #4CAF50;
      padding-left: 10px;
    }
    .report-card {
      background: #fff;
      border: 1px solid #ddd;
      padding: 15px;
      margin: 15px 0;
      border-radius: 5px;
    }
    .summary-text {
      background: #e8f5e9;
      padding: 20px;
      border-radius: 8px;
      margin: 20px 0;
    }
    .footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 2px solid #ddd;
      text-align: center;
      color: #666;
      font-size: 12px;
    }
    .disclaimer {
      background: #fff3cd;
      border: 1px solid #ffc107;
      padding: 15px;
      border-radius: 5px;
      margin: 20px 0;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Comprehensive Health Summary</h1>
    <p>Generated on ${new Date().toLocaleDateString()}</p>
  </div>

  <div class="patient-info">
    <h3>Patient Information</h3>
    <p><strong>Name:</strong> ${summaryData.patientName}</p>
    <p><strong>Age:</strong> ${summaryData.age} years</p>
    <p><strong>Gender:</strong> ${summaryData.gender}</p>
    <p><strong>Blood Group:</strong> ${
      summaryData.bloodGroup || "Not specified"
    }</p>
  </div>

  <div class="section">
    <h2>Reports Analyzed</h2>
    ${summaryData.reports
      .map(
        (report, index) => `
      <div class="report-card">
        <h4>${index + 1}. ${report.type}</h4>
        <p><strong>Date:</strong> ${new Date(
          report.date
        ).toLocaleDateString()}</p>
        <p><strong>Hospital:</strong> ${report.hospital || "Not specified"}</p>
      </div>
    `
      )
      .join("")}
  </div>

  <div class="section">
    <h2>Health Summary</h2>
    <div class="summary-text">
      ${summaryData.summary.replace(/\n/g, "<br>")}
    </div>
  </div>

  <div class="disclaimer">
    <strong>⚠️ Important Disclaimer:</strong><br>
    This health summary is generated by AI and is for informational purposes only. 
    It should not be considered as medical advice, diagnosis, or treatment. 
    Always consult with qualified healthcare professionals for medical concerns.
  </div>

  <div class="footer">
    <p>Generated by Health Records Management System</p>
    <p>This is a confidential medical document</p>
  </div>
</body>
</html>
    `;

    await page.setContent(htmlContent, { waitUntil: "networkidle0" });

    const pdfBuffer = await page.pdf({
      format: "A4",
      margin: { top: "20px", right: "20px", bottom: "20px", left: "20px" },
      printBackground: true,
    });

    console.log("Health summary PDF generated");

    return pdfBuffer;
  } catch (error) {
    console.error("Health summary PDF error:", error);
    throw new Error(`Failed to generate health summary PDF: ${error.message}`);
  } finally {
    if (browser) {
      await browser.close();
    }
  }
};
